<h1>Satyam Kumar</h1>
<p>I'm a B.Tech Second Year Student (in Mechanical Engineering Branch) at BIT Mesra</p>
<img src="https://scontent.fpat1-1.fna.fbcdn.net/v/t39.30808-6/359725031_1431992344312705_4053845332405602379_n.jpg?stp=dst-jpg_p180x540&_nc_cat=103&ccb=1-7&_nc_sid=5f2048&_nc_ohc=vvmn8TG7te0Q7kNvgEAHFas&_nc_ht=scontent.fpat1-1.fna&oh=00_AYCWZxXC-XKE9LOq--H_E6ViigPezA94lTP_YyfsnpP1Uw&oe=666CDAA1" height="150px" width="150px">
<h2>Education</h2>
<ul>
    <li><b>10th Class: </b>94.8%</li>
    <li><b>12th Class: </b> 89.6%</li>
    <li><b>B.Tech Second Year in Mech at BIT Mesra</b>: CGPA 1st Sem-8.96 & 2nd Sem-8.77</li>
</ul>
<h2>Skills</h2>
<ul>
    <li><b>HTML, CSS, JavaScript</b></li>
    <li><b>C, C++</b></li>
    <li><b>MS Excel, MS PowerPoint</b></li>
    <li><b>Node JS, SQL</b></li>
</ul>
<h2>Hobbies</h2>
<ul>
    <li><b>Graphic Designing</b></li>
    <li><b>Video Editing</b></li>
    <li><b>Cricket Analysis</b></li>
    <li><b>Political Analysis</b></li>
    <li><b>Gaming in BGMI and Free Fire</b></li>
</ul>
<h2>Contact Me</h2>
<ul>
    <li><b>Email ID: </b><u>barnwalsatyam12m@outlook.com</u></li>
    <li><b><a href="https://twitter.com/brucehindu1205"> X(Twitter)</a></b></li>
    <li><b><a href="https://www.facebook.com/satyamkumar.barnwal.79/">FaceBook</a></b></li>
    <li><b><a href="https://www.instagram.com/rocksat12m/">Instagram</a></b></li>
    <li><b><a href="https://www.linkedin.com/in/satyam-kumar-4a7a7a194/">Linkedin</a></b></li>
</ul>
<br>
<p>Made with love ❤️ by Satyam Kumar</p>
